#######################################################
# 
# DataSerializerXML.py
# Python implementation of the Class DataSerializerXML
# Generated by Enterprise Architect
# Created on:      17-ห่๏-2015 16:23:02
# Original author: user
# 
#######################################################
from NovaPoshta.Models.DataContainer import DataContainer
from NovaPoshta.Core.Serializer.SerializerInterface import SerializerInterface

class DataSerializerXML(SerializerInterface):
    def serializeData(data):
        pass

    def unserializeData(xml):
        pass

    def __arrayToObject(d):
        pass

    def __objectItemToArray(data, parent = null):
        pass

    def __recursiveSerialize(xml, data):
        pass