#######################################################
# 
# SerializerFactory.py
# Python implementation of the Class SerializerFactory
# Generated by Enterprise Architect
# Created on:      17-���-2015 16:23:04
# Original author: user
# 
#######################################################

from NovaPoshta.Core.Serializer.DataSerializerJSON import DataSerializerJSON
from NovaPoshta.Core.Serializer.DataSerializerJSONRPC2 import DataSerializerJSONRPC2


class SerializerFactory:
    __serializer = None

    def __new__(cls):
        if not hasattr(cls, 'instance'):
            cls.instance = super(SerializerFactory, cls).__new__(cls)
            # cls.instance.__serializer = DataSerializerJSON()
            cls.instance.__serializer = DataSerializerJSONRPC2()
        return cls.instance

    @staticmethod
    def getSerializer():
        return SerializerFactory().__serializer