#######################################################
# 
# Config.py
# Python implementation of the Class Config
# Generated by Enterprise Architect
# Created on:      17-���-2015 16:23:01
# Original author: user
# 
#######################################################
from NovaPoshta.Core.Logger.InterfaceLogger import InterfaceLogger

class Config:
    """Конфиг  Class Config
      @package NovaPoshta
    """
    # Формат данных в формате JSON
    FORMAT_JSON = 'json'
    # Формат данных в формате JSONRPC2
    FORMAT_JSONRPC2 = 'jsonrpc2'
    # Формат данных в формате XML
    FORMAT_XML = 'xml'
    # Возвращать данные на русском языке
    LANGUAGE_UA = 'ua'
    # Возвращать данные на русском языке с API
    # Новой почты (если єто предвидено API Новой
    # почты)
    LANGUAGE_RU = 'ru'
    # Возвращать данные на английский языке с API
    # Новой почты (если єто предвидено API Новой
    # почты)
    LANGUAGE_EN = 'en'
    # @var string API ключ
    __apiKey = '0f220ad7c2ecf2871046ee10e1238465'
    # @var string формат по умолчанию для передачи
    # данных
    __format = 'jsonrpc2'
    # @var string язык по умолчанию для передачи
    # данных
    __language = 'ua'
    # @var string URL API2
    __urlApi = 'https://api.novaposhta.ua/v2.0/'
    # @var string URL личного кабинета Новой Почты
    __urlMyNovaPoshta = 'https://my.novaposhta.ua'

    __classLogger = None

    @staticmethod
    def getApiKey():
        """Возвращает API ключ
           @return string
        """
        return Config.__apiKey

    @staticmethod
    def setApiKey(value):
        """Устанавливает API ключ
           @param $value
        """
        Config.__apiKey = value

    @staticmethod
    def getFormat():
        """Возвращает формат передачи данных
           @return string
        """
        return Config.__format

    @staticmethod
    def setFormat(value):
        """Устанавливает формат передачи данных
           @param $value
        """
        Config.__format = value

    @staticmethod
    def getLanguage():
        """Возвращает язык для ответа с Новой почты
           @return string
        """
        return Config.__language

    @staticmethod
    def setLanguage(value):
        """Устанавливает язык для ответа с Новой
        почты
           @param $value
        """
        Config.__language = value

    @staticmethod
    def getUrlApi():
        """Возвращает URL API2
           @return string
        """
        return Config.__urlApi

    @staticmethod
    def getUrlMyNovaPoshta():
        """Возвращает URL кабинета Новой Почты
           @return string
        """
        return Config.__urlMyNovaPoshta

    @staticmethod
    def setClassLogger(logger):
        """Установить класс для логирования
           @param InterfaceLogger $logger
        """
        Config.__classLogger = logger

    @staticmethod
    def getClassLogger():
        """Получить класс для логирования
           @return InterfaceLogger
        """
        return Config.__classLogger