#######################################################
# 
# DataSerializerJSON.py
# Python implementation of the Class DataSerializerJSON
# Generated by Enterprise Architect
# Created on:      17-���-2015 16:23:02
# Original author: user
# 
#######################################################
from NovaPoshta.Models.DataContainer import DataContainer
from NovaPoshta.Core.Serializer.SerializerInterface import SerializerInterface
import json as jsonSerializer
from NovaPoshta.Models.DataContainerResponse import DataContainerResponse

class DataSerializerJSON(SerializerInterface):
    def serializeData(self, data):
        json = jsonSerializer.dumps(data, default=lambda o: o.__dict__).encode('utf8')

        return json

    def unserializeData(self, json):
        data = jsonSerializer.loads(json)

        dataContainerResponse = DataContainerResponse()

        for (key, value) in data.items():
            if hasattr(dataContainerResponse, key):
                setattr(dataContainerResponse, key, value)

        return dataContainerResponse
