#######################################################
# 
# SerializerInterface.py
# Python implementation of the Interface SerializerInterface
# Generated by Enterprise Architect
# Created on:      17-ห่๏-2015 16:23:04
# Original author: user
# 
#######################################################
from NovaPoshta.Models.DataContainer import DataContainer

class SerializerInterface:
    def serializeData(data):
        """@param DataContainer $data
           @return mixed
        """
        pass

    def unserializeData(data):
        """@param string $data
           @return mixed
        """
        pass