#######################################################
# 
# SerializerBatchInterface.py
# Python implementation of the Interface SerializerBatchInterface
# Generated by Enterprise Architect
# Created on:      17-ห่๏-2015 16:23:04
# Original author: user
# 
#######################################################


class SerializerBatchInterface:
    def serializeBatchData(data):
        """@param array $data
           @return mixed
        """
        pass

    def unserializeBatchData(data):
        """@param string $data
           @return mixed
        """
        pass