#######################################################
# 
# ApiModel.py
# Python implementation of the Class ApiModel
# Generated by Enterprise Architect
# Created on:      17-���-2015 16:23:00
# Original author: user
# 
#######################################################
from NovaPoshta.Core.BaseModel import BaseModel
from NovaPoshta.Core.SendData import SendData
from NovaPoshta.Models.DataContainer import DataContainer


class ApiModel(BaseModel):
    """
    Class ApiModel
      @package NovaPoshta\Core
    """
    # __isBatch = False
    def __construct():
        pass

    def isBatch():
        """Пакетная передача данных
           @return bool
        """
        pass

    def notBatch():
        """Отмена пакетной передачи данных
           @return bool
        """
        pass

    def getThisData():
        pass

    def objectInObject(fromObject, inObject):
        pass

    def _sendData(self, methodName, data=None):
        dataContainer = DataContainer()
        dataContainer.apiKey = None
        dataContainer.calledMethod = methodName
        dataContainer.methodProperties = data
        dataContainer.modelName = self.__getCalledModel(self)

        return SendData.send(dataContainer)

    def getResponseBatch():
        """Получить пакетом данные
           @return array
        """
        pass

    def __getCalledModel(self, self2 = None):
        if self2 is None:
            return self.__name__
        return self.__class__.__name__