#######################################################
# 
# BaseModel.py
# Python implementation of the Class BaseModel
# Generated by Enterprise Architect
# Created on:      17-���-2015 16:23:01
# Original author: user
# 
#######################################################


class BaseModel:
    def __getattr__(self, item):
        if item in self.__dict__:
            return getattr(self, item)
        return None

    def __set(name, value):
        pass

    def __get(name):
        pass
