#######################################################
# 
# NovaPoshtaException.py
# Python implementation of the Class NovaPoshtaException
# Generated by Enterprise Architect
# Created on:      17-ห่๏-2015 16:23:04
# Original author: user
# 
#######################################################


class NovaPoshtaException(Exception):
    pass