#######################################################
# 
# SendData.py
# Python implementation of the Class SendData
# Generated by Enterprise Architect
# Created on:      17-���-2015 16:23:04
# Original author: user
# 
#######################################################
from NovaPoshta.Models.DataContainer import DataContainer
from NovaPoshta.Core.Serializer.SerializerFactory import SerializerFactory
import urllib.request

class SendData:
    """Class SendData
      @package NovaPoshta\Core
    """
    __serializer = None

    def __new__(cls):
        if not hasattr(cls, 'instance'):
            cls.instance = super(SendData, cls).__new__(cls)
            cls.instance.__serializer = SerializerFactory.getSerializer()
        return cls.instance

    def _instance():
        return SendData()

    def send(dataContainer, isBatch=False):
        return SendData._instance()._send(dataContainer)

    def _send(self, dataContainer, isBatch=False):
        dataContainer.id = 1
        data = self.__serializer.serializeData(dataContainer)
        response = self._query(data)
        response = self.__serializer.unserializeData(response)

        return response

    def _query(self, data):
        # response = urllib.request.Request('https://api.novaposhta.ua/v2.0/json/', data=data,
        response = urllib.request.Request('https://api.novaposhta.ua/v2.0/jsonrpc2/', data=data,
                             headers={'content-type': 'application/json'})
        response = urllib.request.urlopen(response)
        response = response.read().decode("utf-8")

        return response

    def getResponseBatch():
        pass

    def _getResponseBatch():
        """@return array
        """
        pass

    def getIdBatch():
        """@return int
        """
        pass

    def query(data):
        """@param $data
           @return bool|mixed
        """
        pass