# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-03 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_slugfield_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='metatag_keyworlds',
            field=models.CharField(max_length=255, null=True, verbose_name='Keywords'),
        ),
    ]
