#######################################################
# 
# Helper.py
# Python implementation of the Class Helper
# Generated by Enterprise Architect
# Created on:      17-ห่๏-2015 16:23:02
# Original author: user
# 
#######################################################


class Helper:
    """Class Helper
      @package NovaPoshta\Core
    """
    pass