#######################################################
# 
# BaseLogger.py
# Python implementation of the Class BaseLogger
# Generated by Enterprise Architect
# Created on:      17-ห่๏-2015 16:23:00
# Original author: user
# 
#######################################################
from NovaPoshta.Core.Logger.DataLogger import DataLogger

class BaseLogger:
    def setDataLogger(dataLogger):
        pass