#######################################################
# 
# InterfaceLogger.py
# Python implementation of the Interface InterfaceLogger
# Generated by Enterprise Architect
# Created on:      17-���-2015 16:23:02
# Original author: user
# 
#######################################################


class InterfaceLogger:
    """Логирования Interface Logger
      @package NovaPoshta\Core
    """
    def setOriginalData(toData, fromData):
        """Данные оригинальные (сырые данные, в тому
        формате в котором отправляется запрос)
           @param $fromData string запрос
           @param $toData string ответ
           @return mixed
        """
        pass

    def setData(toData, fromData):
        """Данные объектов запроса/ответа
           @param $fromData
           @param $toData
           @return mixed
        """
        pass