#######################################################
# 
# DataLogger.py
# Python implementation of the Class DataLogger
# Generated by Enterprise Architect
# Created on:      17-ห่๏-2015 16:23:02
# Original author: user
# 
#######################################################


class DataLogger:
    toData = null
    toOriginalData = null
    fromOriginalData = null
    fromData = null